### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by havardAasen** [coin-or-tools/Data-Netlib#2]
As it stands, it is difficult to know which license this project uses, one of the few files that is not auto-generated and has a copyright header is _Makefile.am_, and reading that, it seems that either `EPL-1.0` or `EPL-2.0` is the correct one.

Would you be kind to add a LICENSE file to this project?

I can provide a pr if you want.

**Comment by havardAasen** [comment]
Will @tkralphs or @svigerske please take a look at this?

**Comment by svigerske** [comment]
I added a LICENSE with 721b27fb, but as far as I recall, the problem here is that we don't know what license the netlib instances are under. I would assume that they are public domain, but https://www.netlib.org/lp/data/readme doesn't say anything.
